---
- hosts: 172.31.38.130
  become: yes
  tasks: 
  - name: i want to execute linux command
    command: hostname -f
    register: myresult

  - name: i want to display my first task result
    debug: 
     msg: "{{myresult}}"

  - name: want to install git
    apt: 
     name: git
     state: present
    when: myresult.stderr ==""

  - name: want to install tree
    apt: 
     name: tree
     state: present
    when: myresult.stderr !=""