---
- hosts: 172.31.38.130
  become: yes
  tasks: 
  - include_tasks: myfile.yml

  - name: install webserver
    apt: 
     name: apache2
     state: present
    notify: restartwebserver

  - name: i want to copy my index file
    template: 
     src: myindex.j2
     dest: /var/www/html/index.html
    notify: restartwebserver

  - name: download file from internet
    get_url:
     url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
     dest: /home/ubuntu/jenkins.war
     force_basic_auth: yes
    notify: restartwebserver

  handlers:
  - name: restartwebserver
    service:
     name: apache2
     state: restarted