---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt: 
     name: "{{myjavapackageforUbuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: install java on redhat
    yum: 
     name: "{{myjavapackageforRedHat}}"
     state: present
    when: ansible_os_family =="RedHat"