---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to install webserver
    apt: 
     name: "{{mywebpackageforUbuntu}}"
     state: present
    when: ansible_os_family =="Debian"

  - name: i want to start my webserver
    service: 
     name: "{{mywebpackageforUbuntu}}"
     state: started
    when: ansible_os_family =="Debian"

  - name: install webserver on RedHat
    yum: 
     name: "{{mywebpackageforRedHat}}"
     state: present
    when: ansible_os_family =="RedHat"

  - name: want to start webserver
    service: 
     name: "{{mywebpackageforRedHat}}" 
     state: started
    when: ansible_os_family =="RedHat"